name: Run Tests, Build App

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Checkout Submodules
      uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Run Lint
      run: ./gradlew lint --console plain

    - name: Run Unit Tests
      run: ./gradlew test --console plain

    - name: Build Example App
      run: ./gradlew :example:assembleRelease
